// DO NOT EDIT — generated by `npm run contract:generate` from src/lib/api/contract/openapi.json
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
    readonly "/api/changes": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** `GET /api/changes` — recent changes (working tree + commits). */
        readonly get: operations["listChanges"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/compliance/export": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * `GET /api/compliance/export` — generate a tamper-evident `.zip` of SOC2
         *     evidence on the fly and return it as a binary download.
         * @description The zip contains `manifest.json` (SHA-256 + size of every other file),
         *     `manifest.sig` + `manifest.pub` (Ed25519 signature over the manifest
         *     bytes and the verifying key, reusing the repo's keypair so the existing
         *     offline verifier can validate the export), `ledger.csv` (all committed
         *     provenance records), `verification_history.csv` (CI gate pass/fail
         *     records), and `adr/*.md` (generated MADR-format ADRs tied to the ledger).
         *
         *     All SQLite + zip + SHA-256 + Ed25519 work runs inside
         *     `tokio::task::spawn_blocking`; the handler only attaches the
         *     `application/zip` + `Content-Disposition: attachment` headers to the
         *     returned `Response`. Empty / no-DB state still yields a valid zip
         *     (header-only CSVs, no `adr/` files, a manifest over the files that
         *     exist, and a signature over that manifest) — 200, not an error.
         *     `GET /api/compliance/export` — download a tamper-evident SOC2 evidence
         *     `.zip`. Returns `application/zip` with `Content-Disposition: attachment`.
         */
        readonly get: operations["exportComplianceEvidence"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/compliance/signatures": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** `GET /api/compliance/signatures` — recent signature status entries. */
        readonly get: operations["getComplianceSignatures"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/compliance/summary": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** `GET /api/compliance/summary` — aggregate compliance summary. */
        readonly get: operations["getComplianceSummary"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/config": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** `GET /api/config` — daemon configuration (secrets redacted). */
        readonly get: operations["getConfig"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/endpoints/changed": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** `GET /api/endpoints/changed` — API contracts affected by changed files. */
        readonly get: operations["getEndpointsChanged"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/hotspots": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** `GET /api/hotspots` — hotspot rankings. */
        readonly get: operations["listHotspots"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/hotspots/trend": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** `GET /api/hotspots/trend` — rolling hotspot trend series. */
        readonly get: operations["getHotspotTrend"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/knowledge-graph": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** `GET /api/knowledge-graph` — CozoDB knowledge-graph subgraph. */
        readonly get: operations["getKnowledgeGraph"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/ledger": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** `GET /api/ledger` — transaction table, paginated. */
        readonly get: operations["listLedger"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/ledger/search": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** `GET /api/ledger/search` — full-text search over ledger entries. */
        readonly get: operations["searchLedger"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/ledger/{tx_id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** `GET /api/ledger/{tx_id}` — single transaction detail. */
        readonly get: operations["getLedgerDetail"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/projects": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** `GET /api/projects` — project list (local + discovered siblings). */
        readonly get: operations["getProjects"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/reports/latest-impact.json": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * `GET /api/reports/latest-impact.json` — passthrough of the latest impact
         *     report JSON. Returns `application/json` with an opaque object schema when
         *     a report exists; 404 otherwise.
         */
        readonly get: operations["getLatestImpactReport"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/reports/latest-verify.json": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * `GET /api/reports/latest-verify.json` — passthrough of the latest verify
         *     report JSON. Returns `application/json` with an opaque object schema when
         *     a report exists; 404 otherwise.
         */
        readonly get: operations["getLatestVerifyReport"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/security/boundaries": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** `GET /api/security/boundaries` — security boundary counts and edges. */
        readonly get: operations["getSecurityBoundaries"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/session": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** `GET /api/session` — current user session. */
        readonly get: operations["getSession"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/snapshot": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** `GET /api/snapshot` — summary metrics + recent change feed. */
        readonly get: operations["getSnapshot"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/status": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * `GET /api/status` — overall daemon / project health.
         * @description **Intentional divergence:** this endpoint returns a bare `StatusResponse`
         *     rather than the standard `WithSource<T>` wrapper used by dashboard data
         *     surfaces. Status is a health surface; surfacing daemon failures directly is
         *     more useful than substituting mock data. This is deferred item #30, now
         *     documented in `coordination.md` §4.8.
         */
        readonly get: operations["getStatus"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/sync/status": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * `GET /api/sync/status` — local M0 sync state.
         * @description **Feature gate:** the route is **always registered** (track 0013 DoD-1).
         *     When built **with** `sync`, the handler reads `SyncState` from the ledger
         *     DB and returns real sync metadata. When built **without** `sync`, it
         *     returns a `501 Not Implemented` — the schema documents the route, and the
         *     runtime honors it: no documented-but-unserved route, no dangling handler.
         */
        readonly get: operations["getSyncStatus"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/verify/health": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** `GET /api/verify/health` — overall verification health. */
        readonly get: operations["getVerifyHealth"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/verify/history": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** `GET /api/verify/history` — pass/fail trend over time. */
        readonly get: operations["getVerifyHistory"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/verify/steps": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** `GET /api/verify/steps` — per-step verification aggregates. */
        readonly get: operations["getVerifySteps"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/health": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** `GET /health` — daemon liveness check. Does **not** require auth. */
        readonly get: operations["getHealth"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
};
export type webhooks = Record<string, never>;
export type components = {
    schemas: {
        readonly AffectedContract: {
            readonly endpoint_id: string;
            readonly method: string;
            readonly path: string;
            /** Format: float */
            readonly similarity: number;
            readonly spec_file: string;
            readonly summary: string;
        };
        readonly ChangeResponse: {
            readonly additions: number;
            readonly author: string;
            readonly deletions: number;
            readonly fileCount: number;
            readonly id: string;
            readonly path: string;
            readonly risk: string;
            readonly status: string;
            readonly summary: string;
            readonly timeAgo: string;
        };
        readonly ChangedFileResponse: {
            /** Format: int64 */
            readonly additions: number;
            /** Format: int64 */
            readonly deletions: number;
            readonly path: string;
        };
        readonly ChangesQuery: {
            /** Format: int64 */
            readonly days?: number | null;
            readonly working_tree?: boolean | null;
        };
        /**
         * @description `GET /api/compliance/signatures` — per-entry signature status for the
         *     recent ledger.
         *
         *     Returns a bare JSON array of `{ txId, entity, summary, committedAt,
         *     status, category }` (camelCase) sorted by `committed_at` DESC, bounded to
         *     the most recent `COMPLIANCE_SIGNATURES_LIMIT` (100) entries.
         *
         *     `status` is the string `VALID` | `INVALID` | `SKIPPED`:
         *     - `(Some(sig), Some(pub))` → `verify_signature(...)` → `VALID` if true,
         *       else `INVALID`.
         *     - otherwise (no signature) → `INVALID` when `intent.require_signing` is
         *       true (the CLI labels this `UNSIGNED`; the dashboard status set is
         *       `{VALID,INVALID,SKIPPED}` per the E2 spec, so `UNSIGNED` maps to
         *       `INVALID`), else `SKIPPED`.
         *
         *     `category` is the `Category` enum's `Display` form (e.g. `"FEATURE"`).
         *
         *     No-DB path → empty array `[]` (200, not an error).
         */
        readonly ComplianceSignatureEntry: {
            readonly category: string;
            readonly committedAt: string;
            readonly entity: string;
            readonly status: string;
            readonly summary: string;
            readonly txId: string;
        };
        /**
         * @description `GET /api/compliance/summary` — aggregate cryptographic validity and audit
         *     completion rates over the ledger, plus the recent hotspot delta.
         *
         *     Response (camelCase):
         *     - `totalSigned`: count of ledger entries with BOTH `signature` and
         *       `public_key` present (i.e. signed rows, regardless of whether the
         *       signature currently verifies).
         *     - `validityPercent`: `valid_count / total_entries * 100.0` rounded to 2dp,
         *       where `valid_count` is the number of entries whose signature verifies
         *       against the stored public key (or, for unsigned rows when
         *       `intent.require_signing` is false, the row is NOT counted as valid —
         *       only cryptographically VALID rows contribute). `0.0` when there are no
         *       entries.
         *     - `lastAuditAt`: the most recent `committed_at` among entries classified
         *       VALID (the last verifiably-signed event). `null` when there are no
         *       VALID entries / no entries. This field is intentionally NOT
         *       `skip_serializing_if`-gated — the frontend contract is
         *       `lastAuditAt: string | null`, so it MUST serialize as `null` in the
         *       empty state (matches E1's `lastRunAt` contract).
         *     - `hotspotDeltaPercent`: see `fetch_hotspot_delta_percent`.
         *
         *     No-DB path (ledger.db absent): returns
         *     `{ totalSigned: 0, validityPercent: 0.0, lastAuditAt: null,
         *     hotspotDeltaPercent: 0.0 }` with HTTP 200 — the dashboard empty state,
         *     NOT an error.
         */
        readonly ComplianceSummaryResponse: {
            /** Format: double */
            readonly hotspotDeltaPercent: number;
            readonly lastAuditAt?: string | null;
            /** Format: int64 */
            readonly totalSigned: number;
            /** Format: double */
            readonly validityPercent: number;
        };
        readonly ConfigResponse: {
            readonly graph_path: string;
            readonly ledger_path: string;
            readonly llm_backend: string;
            readonly polling_interval: string;
            readonly project: string;
            readonly repo_path: string;
            readonly signing_key: string;
            readonly telemetry: string;
            readonly version: string;
        };
        /**
         * @description Frontend-facing hotspot DTO decoupled from the internal `Hotspot` domain
         *     struct. The internal struct (`intelligence::Hotspot`) is coupled to the
         *     impact math module; this DTO gives the API a stable contract that the
         *     frontend can rely on even if the internal struct changes.
         *
         *     Backward-compat fields (`displayScore`, `score`, `complexity`, `frequency`,
         *     `centrality`) are included temporarily until the frontend PR merges. They
         *     will be removed once the frontend consumes the new fields directly.
         */
        readonly HotspotResponse: {
            readonly centrality?: number | null;
            /** Format: int32 */
            readonly changeCount: number;
            /** Format: int32 */
            readonly complexity: number;
            readonly contributor?: string | null;
            /** Format: float */
            readonly displayScore: number;
            readonly filePath: string;
            /** Format: double */
            readonly frequency: number;
            readonly id: string;
            readonly lastTouchedAt?: string | null;
            readonly rank: number;
            readonly riskLevel: string;
            /** Format: float */
            readonly riskScore: number;
            /** Format: float */
            readonly score: number;
        };
        readonly HotspotTrendQuery: {
            /** Format: int64 */
            readonly days?: number | null;
            readonly limit?: number | null;
        };
        readonly HotspotTrendResponse: {
            readonly labels: readonly string[];
            readonly series: readonly components["schemas"]["HotspotTrendSeries"][];
            readonly truncated: boolean;
        };
        readonly HotspotTrendSeries: {
            readonly path: string;
            readonly scores: readonly number[];
        };
        readonly HotspotsQueryParams: {
            /** Format: int64 */
            readonly days?: number | null;
            readonly limit?: number | null;
        };
        readonly KgEdge: {
            /** Format: double */
            readonly confidence?: number | null;
            readonly provenance_id?: string | null;
            readonly relation: string;
            readonly source: string;
            readonly target: string;
        };
        readonly KgNode: {
            readonly category: string;
            /** Format: int32 */
            readonly complexity: number;
            readonly file_path: string;
            readonly id: string;
            readonly label: string;
            readonly metadata?: unknown;
            /** Format: double */
            readonly risk_score: number;
        };
        readonly KnowledgeGraphQuery: {
            readonly focus?: string | null;
            readonly limit?: number | null;
        };
        readonly KnowledgeGraphResponse: {
            readonly edges: readonly components["schemas"]["KgEdge"][];
            readonly nodes: readonly components["schemas"]["KgNode"][];
            readonly truncated: boolean;
        };
        /** @description Detail response for a single ledger transaction, including enriched fields. */
        readonly LedgerDetailResponse: components["schemas"]["LedgerEntryResponse"] & {
            readonly files: readonly components["schemas"]["ChangedFileResponse"][];
            readonly flakes: number;
            readonly hotspots_crossed: number;
            readonly tests_run: number;
        };
        readonly LedgerEntryResponse: {
            readonly author: string;
            readonly category: string;
            readonly change_type: string;
            readonly committed_at: string;
            readonly entity: string;
            readonly entity_normalized: string;
            readonly entry_type: string;
            /** Format: int64 */
            readonly id: number;
            readonly is_breaking: boolean;
            readonly origin: string;
            readonly outcome_notes?: string | null;
            readonly public_key?: string | null;
            readonly reason: string;
            readonly related_tickets?: string | null;
            readonly risk?: string | null;
            readonly signature?: string | null;
            readonly summary: string;
            readonly trace_id?: string | null;
            readonly tx_id: string;
            readonly verification_basis?: string | null;
            readonly verification_status?: string | null;
        };
        readonly LedgerListQuery: {
            readonly category?: string | null;
            readonly limit?: number | null;
            readonly offset?: number | null;
        };
        readonly LedgerSearchQuery: {
            /** Format: int64 */
            readonly days?: number | null;
            readonly limit?: number | null;
            readonly offset?: number | null;
            readonly q?: string | null;
        };
        /**
         * @description RFC 7807 problem-detail object. Additional members are allowed; this shape
         *     supplies the core fields required by the track contract.
         *
         *     Track 0013: `ToSchema` + `pub(crate)` so the OpenAPI can document error
         *     response bodies (e.g. the 501 from `/api/sync/status` when built without
         *     the `sync` feature).
         */
        readonly ProblemDetail: {
            readonly detail: string;
            /** Format: int32 */
            readonly status: number;
            readonly title: string;
            readonly type: string;
        };
        readonly ProjectResponse: {
            /** Format: int32 */
            readonly health_score: number;
            readonly id: string;
            readonly last_scan_at?: string | null;
            readonly name: string;
            readonly path: string;
            readonly status: string;
            /**
             * @description TA31 R1: per-sibling validation warnings (e.g. an empty ledger
             *     `entity`). Always present (empty for the local/root project and
             *     for fully-valid siblings) so the frontend can render a "needs
             *     attention" badge without an `Option` round-trip. This is
             *     additive/non-breaking relative to the pre-TA31 DTO shape.
             */
            readonly validation_warnings: readonly string[];
        };
        readonly SecurityBoundariesResponse: {
            readonly boundaries: unknown;
            readonly meta: unknown;
        };
        readonly SnapshotResponse: {
            readonly graph_edges: number;
            readonly graph_nodes: number;
            readonly indexed_documents: number;
            readonly last_audit?: string | null;
            readonly overall_risk: string;
            readonly pending_transactions: number;
            readonly project_id: string;
            readonly recent_changes: readonly components["schemas"]["ChangeResponse"][];
            readonly top_hotspots: readonly components["schemas"]["HotspotResponse"][];
            readonly unaudited_drift: number;
        };
        readonly StatusResponse: {
            readonly completion_model_reachable: boolean;
            readonly embedding_model_reachable: boolean;
            readonly graph_ready: boolean;
            readonly index_ready: boolean;
            readonly pending_transactions: number;
            readonly unaudited_drift: number;
        };
        /**
         * @description `SyncStatusResponse` DTO — local M0 sync state.
         *
         *     Deliberately **not** gated on `#[cfg(feature = "sync")]` so the OpenAPI
         *     schema can document the route in all builds (schema/runtime consistency,
         *     track 0013 DoD-1). Only the sync-specific *logic* (reading `SyncState`
         *     from the ledger DB) is feature-gated; the DTO and the route are always
         *     present. When built without `sync`, the handler returns a clean
         *     `501 Not Implemented` (see `sync_status_handler`).
         */
        readonly SyncStatusResponse: {
            readonly device_id?: string | null;
            readonly last_apply_at?: string | null;
            readonly last_extract_at?: string | null;
            readonly last_run_at?: string | null;
        };
        readonly UserSession: {
            readonly email: string;
            readonly id: string;
            readonly name: string;
            readonly role: string;
        };
        /**
         * @description `GET /api/verify/health` — overall verification health derived from the
         *     latest `verification_runs` row.
         *
         *     Status mapping (documented for the reviewer):
         *     - No runs recorded → `DEGRADED` with `message = "No verification runs
         *       recorded"` and `lastRunAt = null`. This is NOT an error (200, not 404)
         *       so the dashboard can render its empty state.
         *     - Latest run `overall_pass = false` → `FAILING`.
         *     - Latest run `overall_pass = true` but older than 7 days → `DEGRADED`
         *       with `message = "Last verification run is stale (older than 7 days)"`.
         *       (A stale failing run stays `FAILING` — failure takes precedence over
         *       staleness.)
         *     - Otherwise → `HEALTHY`.
         */
        readonly VerificationHealthResponse: {
            readonly lastRunAt?: string | null;
            readonly message?: string | null;
            readonly status: string;
        };
        /**
         * @description `GET /api/verify/steps` — per-step aggregates across all history.
         *
         *     Returns a bare JSON array of `{ id, name, lastRunAt, averageDurationMs,
         *     passRatePercent, recentFailures }` sorted ascending by step command.
         *
         *     `id` is the step's stable identifier (its `command` — the verify plan step
         *     `src/verify/plan.rs::VerificationStep` has no separate id field, and
         *     `verification_results` only stores `command`). `name` is the friendly
         *     label: the step's `description` from the most recent `verification_runs.
         *     plan_json` that contains a step with that command, falling back to
         *     `command` when no plan_json is available, fails to parse, or has no
         *     matching step. `plan_json` is a serialized `VerificationPlan` (see
         *     `verify::engine::persist_verify_report`); parse errors on any single row
         *     are skipped so one malformed run cannot fail the whole endpoint.
         *
         *     `recentFailures` counts failures within the last 10 verification runs
         *     (by `verification_runs.id DESC`). Flagged as an assumption.
         */
        readonly VerificationStepResponse: {
            /** Format: double */
            readonly averageDurationMs: number;
            readonly id: string;
            readonly lastRunAt: string;
            readonly name: string;
            /** Format: double */
            readonly passRatePercent: number;
            /** Format: int64 */
            readonly recentFailures: number;
        };
        readonly VerificationTrendPoint: {
            readonly date: string;
            /** Format: int64 */
            readonly failed: number;
            /** Format: int64 */
            readonly passed: number;
        };
        /**
         * @description `GET /api/verify/history?days=30` — per-date pass/fail counts over the
         *     last `days` days (default 30, accepts 90). Returns a bare JSON array of
         *     `{ date, passed, failed }` sorted ascending by date. Dates with no runs
         *     are omitted (deterministic: only dates that have at least one run appear).
         */
        readonly VerifyHistoryQuery: {
            /** Format: int64 */
            readonly days?: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
};
export type $defs = Record<string, never>;
export interface operations {
    readonly listChanges: {
        readonly parameters: {
            readonly query?: {
                readonly days?: number | null;
                readonly working_tree?: boolean | null;
            };
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Recent changes */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": readonly components["schemas"]["ChangeResponse"][];
                };
            };
        };
    };
    readonly exportComplianceEvidence: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description SOC2 evidence ZIP */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/zip": unknown;
                };
            };
        };
    };
    readonly getComplianceSignatures: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Compliance signature entries */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": readonly components["schemas"]["ComplianceSignatureEntry"][];
                };
            };
        };
    };
    readonly getComplianceSummary: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Compliance summary */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ComplianceSummaryResponse"];
                };
            };
        };
    };
    readonly getConfig: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Daemon configuration */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ConfigResponse"];
                };
            };
        };
    };
    readonly getEndpointsChanged: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Affected API contracts */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": readonly components["schemas"]["AffectedContract"][];
                };
            };
        };
    };
    readonly listHotspots: {
        readonly parameters: {
            readonly query?: {
                readonly limit?: number | null;
                readonly days?: number | null;
            };
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Hotspot rankings */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": readonly components["schemas"]["HotspotResponse"][];
                };
            };
        };
    };
    readonly getHotspotTrend: {
        readonly parameters: {
            readonly query?: {
                readonly days?: number | null;
                readonly limit?: number | null;
            };
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Hotspot trend data */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HotspotTrendResponse"];
                };
            };
        };
    };
    readonly getKnowledgeGraph: {
        readonly parameters: {
            readonly query?: {
                readonly limit?: number | null;
                readonly focus?: string | null;
            };
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Knowledge graph nodes and edges */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["KnowledgeGraphResponse"];
                };
            };
        };
    };
    readonly listLedger: {
        readonly parameters: {
            readonly query?: {
                readonly category?: string | null;
                readonly limit?: number | null;
                readonly offset?: number | null;
            };
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Ledger entries */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": readonly components["schemas"]["LedgerEntryResponse"][];
                };
            };
        };
    };
    readonly searchLedger: {
        readonly parameters: {
            readonly query?: {
                readonly q?: string | null;
                readonly days?: number | null;
                readonly limit?: number | null;
                readonly offset?: number | null;
            };
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Matching ledger entries */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": readonly components["schemas"]["LedgerEntryResponse"][];
                };
            };
            /** @description Missing search query */
            readonly 400: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly getLedgerDetail: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                /** @description Transaction ID */
                readonly tx_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Ledger entry detail */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["LedgerDetailResponse"];
                };
            };
            /** @description Transaction not found */
            readonly 404: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly getProjects: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Project list */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": readonly components["schemas"]["ProjectResponse"][];
                };
            };
        };
    };
    readonly getLatestImpactReport: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Latest impact report JSON */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": Record<string, never>;
                };
            };
            /** @description Report not found */
            readonly 404: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly getLatestVerifyReport: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Latest verify report JSON */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": Record<string, never>;
                };
            };
            /** @description Report not found */
            readonly 404: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly getSecurityBoundaries: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Security boundaries */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["SecurityBoundariesResponse"];
                };
            };
        };
    };
    readonly getSession: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Current session */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["UserSession"];
                };
            };
        };
    };
    readonly getSnapshot: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Project snapshot */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["SnapshotResponse"];
                };
            };
        };
    };
    readonly getStatus: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Daemon status */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
    readonly getSyncStatus: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Local sync state */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["SyncStatusResponse"];
                };
            };
            /** @description Sync feature not enabled in this build — rebuild with --features sync */
            readonly 501: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    readonly getVerifyHealth: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Verification health */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["VerificationHealthResponse"];
                };
            };
        };
    };
    readonly getVerifyHistory: {
        readonly parameters: {
            readonly query?: {
                readonly days?: number | null;
            };
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Verification history points */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": readonly components["schemas"]["VerificationTrendPoint"][];
                };
            };
        };
    };
    readonly getVerifySteps: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Verification step metrics */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": readonly components["schemas"]["VerificationStepResponse"][];
                };
            };
        };
    };
    readonly getHealth: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Daemon is live */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": Record<string, never>;
                };
            };
        };
    };
}
